export const guessTheDrawWords = [
  "airplane",
  "anchor",
  "apple",
  "astronaut",
  "backpack",
  "balloon",
  "banana",
  "baseball",
  "beach",
  "bear",
  "bicycle",
  "birthday cake",
  "blanket",
  "book",
  "bridge",
  "butterfly",
  "camera",
  "candle",
  "castle",
  "cat",
  "cherry",
  "cloud",
  "coffee",
  "compass",
  "cookie",
  "crown",
  "diamond",
  "dinosaur",
  "dog",
  "dolphin",
  "dragon",
  "drum",
  "elephant",
  "firetruck",
  "flower",
  "forest",
  "giraffe",
  "guitar",
  "hamburger",
  "headphones",
  "helicopter",
  "ice cream",
  "island",
  "jellyfish",
  "kangaroo",
  "keyboard",
  "kite",
  "ladder",
  "lantern",
  "lighthouse",
  "lion",
  "lollipop",
  "magnet",
  "microphone",
  "moon",
  "mountain",
  "mushroom",
  "octopus",
  "paintbrush",
  "panda",
  "parachute",
  "pencil",
  "penguin",
  "piano",
  "pineapple",
  "pirate",
  "pizza",
  "planet",
  "rainbow",
  "rocket",
  "sandcastle",
  "scissors",
  "shark",
  "ship",
  "skateboard",
  "snowman",
  "spaceship",
  "spider",
  "starfish",
  "strawberry",
  "sunflower",
  "sunglasses",
  "sword",
  "telescope",
  "tent",
  "tiger",
  "toothbrush",
  "tractor",
  "train",
  "treasure chest",
  "treehouse",
  "trophy",
  "turtle",
  "umbrella",
  "unicorn",
  "volcano",
  "whale",
  "windmill",
  "zebra",
] as const;

export function maskGuessTheDrawWord(word: string): string {
  return word
    .split("")
    .map((character) => {
      if (character === " ") {
        return " ";
      }

      return "_";
    })
    .join("");
}

export function getRandomGuessTheDrawWord(): string {
  const randomIndex = Math.floor(Math.random() * guessTheDrawWords.length);
  return guessTheDrawWords[randomIndex];
}
